app:
  inbound:
    file:
      path: src/main/resources/static

spring:
  application:
    name: spring-batch-integration-demo

  batch:
    jdbc:
      initialize-schema: never # always, never, embedded

    job:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # create-drop, create, update, validate, none
      show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/docker
    username: developer
    password: local
    initialize: false # Execute the schema.sql and data.sql files on startup
    continue-on-error: false

management:
  server:
    port: 9091

  info:
    java:
      enabled: true

    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator

  metrics:
    tags:
      application: app-demo
      environment: ${ENVIRONMENT:local}

    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
